openapi: 3.0.0
info:
    title: JOBS-API
    contact: {}
    version: '1.0'
servers:
    - url: https://jobs-api-ejike.herokuapp.com/api/v1
      variables: {}
paths:
    /auth/register:
        post:
            tags:
                - Auth
            summary: Post Register User
            operationId: PostRegisterUser
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PostRegisterUserRequest'
                        example:
                            name: ejike chiboka
                            email: ejike.chiboka@gmail.com
                            password: ejike123
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /auth/login:
        post:
            tags:
                - Auth
            summary: Post Login User
            operationId: PostLoginUser
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PostLoginUserRequest'
                        example:
                            email: sama.adreen@gmail.com
                            password: sama123
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security: []
    /jobs:
        post:
            tags:
                - Jobs
            summary: Post Create Job
            operationId: PostCreateJob
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PostCreateJobRequest'
                        example:
                            company: daily times
                            position: chief editor
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: Get All Jobs
            operationId: GetAllJobs
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
    /jobs/{id}:
        parameters:
            - in: path
              name: id
              schema:
                  type: string
              required: true
              description: The job ID
        get:
            tags:
                - Jobs
            summary: Get A Single Job
            operationId: GetASingleJob
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        patch:
            tags:
                - Jobs
            summary: Update a Single Job
            operationId: UpdateaSingleJob
            parameters: []
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateaSingleJobRequest'
                        example:
                            company: globacom
                            position: CTO
                required: true
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        delete:
            tags:
                - Jobs
            summary: Delete A Job
            operationId: DeleteAJob
            parameters: []
            responses:
                '200':
                    description: ''
                    headers: {}
            deprecated: false
            security:
                - bearer: []
components:
    schemas:
        PostRegisterUserRequest:
            title: PostRegisterUserRequest
            required:
                - name
                - email
                - password
            type: object
            properties:
                name:
                    type: string
                email:
                    type: string
                password:
                    type: string
            example:
                name: ejike chiboka
                email: ejike.chiboka@gmail.com
                password: ejike123
        PostLoginUserRequest:
            title: PostLoginUserRequest
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: sama.adreen@gmail.com
                password: sama123
        PostCreateJobRequest:
            title: PostCreateJobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: daily times
                position: chief editor
        UpdateaSingleJobRequest:
            title: UpdateaSingleJobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: globacom
                position: CTO
    securitySchemes:
        bearer:
            type: http
            scheme: bearer
security: []
tags:
    - name: Misc
      description: ''
    - name: Auth
      description: ''
    - name: Jobs
      description: ''
